# Most of this configuration comes from https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# tmux display things in 256 colors
set -g default-terminal "screen-256color"

set -g history-limit 10000

# Rathen than constraining window size to max size of any client
# connected to the *session*, constrain window size to the max size
# of any client connected to *that window*. More reasonable.
setw -g aggressive-resize on

# Rathen than constraining window size to max size of any client
# connected to the *session*, constrain window size to the max size
# of any client connected to *that window*. More reasonable.
setw -g aggressive-resize on

# Title all windows
unbind =
bind = select-layout tiled

# Activity monitoring
setw -g monitor-activity off
set -g visual-activity off

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
# don't rename windows automatically
set-option -g allow-rename off

# Enable mouse mode (tmux 2.1 and above)
# It might break selecting/copying text.
# To select text as expected hold option to disable it (iTerm2)
set -g mouse on

# reload config file (change file location to your the tmux.conf you want to use)
bind r source ~/.tmux.conf

# Set vi mode:
setw -g mode-keys vi

# Copy from TMUX to clipboard
# bind -t vi-copy y copy-pipe "xclip -sel clip -i"

# Binding keys like vi for copying selecting etc...
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

###################
# List of plugins #
###################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# TMUX-RESURRECT
# Restoring nvim sessions also with resurrect:
# for neovim
set -g @resurrect-strategy-nvim 'session'
# Restore pane contents also
set -g @resurrect-capture-pane-contents 'on'
# for neovim
set-option -sg escape-time 10


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
